ConstrManagementProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path
from drawingdoc.views import HomeView, media_access


urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include(('drawingdoc.urls','project'), namespace='project')),
    path('', HomeView.as_view()),
    path('', include('users.urls')),
    re_path(r'^media/(?P<path>.*)', media_access, name='media')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drawingdoc/urls.py
from django.urls import path, reverse_lazy, include
from django.views.generic import RedirectView

from .views import NewBuildingName, UploadDrawingView, NewProjectView, DrawingsListView, DrawingInfoView, \
    DrawingDeleteView, DrawingUpdateView, ProjectListView, ProjectInfoView, BuildingNameDeleteView,\
    BuildingNameUpdateView, ProjectDeleteView, AddUserToProjectView, MemberOfProjectListView, MemberOfProjectDeleteView



urlpatterns = [
    path('', RedirectView.as_view(url='list/')),
    path('new/', NewProjectView.as_view(), name='project-new'),
    path('list/', ProjectListView.as_view(), name='project-list'),
    path('<int:pk_p>/', ProjectInfoView.as_view(), name='project-info'),
    path('<int:pk_p>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('<int:pk_p>/members/', MemberOfProjectListView.as_view(), name='members'),
    path('<int:pk_p>/members/add/', AddUserToProjectView.as_view(), name='members-add'),
    path('<int:pk_p>/members/<int:pk_m>/delete/', MemberOfProjectDeleteView.as_view(), name='members-delete'),
    path('<int:pk_p>/building_name/<int:pk_bn>/delete/', BuildingNameDeleteView.as_view(),name='building-name-delete'),
    path('<int:pk_p>/building_name/<int:pk_bn>/update/', BuildingNameUpdateView.as_view(),name='building-name-update'),
    path('<int:pk_p>/new_building_name/', NewBuildingName.as_view(), name='building-name-create'),
    path('<int:pk_p>/drawing_documents/upload/', UploadDrawingView.as_view(),name='drawing-document-upload'),
    path('<int:pk_p>/drawing_documents/list/', DrawingsListView.as_view(),name='drawing-document-list'),
    path('<int:pk_p>/drawing_documents/<int:pk>/', DrawingInfoView.as_view(),name='drawing-document-info'),
    path('<int:pk_p>/drawing_documents/<int:pk>/delete/', DrawingDeleteView.as_view()),
    path('<int:pk_p>/drawing_documents/<int:pk>/update/', DrawingUpdateView.as_view()),
    path('<int:pk_p>/schedule/', include('schedule.urls')),
]

schedule/urls.py
from django.urls import path, reverse_lazy, include
from django.views.generic import RedirectView

from .views import UploadCsvView, ScheduleGantView, ScheduleInfoView, ScheduleDeleteView

urlpatterns = [
    path('', ScheduleInfoView.as_view(), name='schedule-info'),
    path('upload/', UploadCsvView.as_view(), name='schedule-upload'),
    path('delete/', ScheduleDeleteView.as_view(), name='schedule-delete'),
    path('view/', ScheduleGantView.as_view(), name='schedule-view'),
]

users/urls.py
from django.urls import path, include
from .views import RegisterUserView, CustomLoginView, CustomLogoutView, activate, activate_info
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('registration/', RegisterUserView.as_view(), name='registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('activating/', activate_info, name='activate-info'),
]

drawingdoc/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from .drawingsnamechecker import drawings_name_checker


# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbreviation = models.CharField(max_length=3, unique=True)
    creator = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class MemberOfProject(models.Model):

    class Status(models.TextChoices):
        s1 = 'AR', _('Architekt')
        s2 = 'INW', _('Inwestor')
        s3 = 'GW', _('Generalny Wykonawca')
        s4 = 'INI', _('Inspektor Nadzoru')

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    status_user_perms = models.CharField(max_length=100, choices=Status.choices, default=Status.s1)


class BuildingName(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbreviation = models.CharField(max_length=3, unique=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def directory_path(instance, filename):
    drawing_data = drawings_name_checker(filename)
    return 'uploads/{project}/{stage}/{branch}/{building_name}/{name}'.format(project=drawing_data['project'],
                                                                              stage=drawing_data['design_stage'],
                                                                              branch=drawing_data['branch'],
                                                                              building_name=drawing_data[
                                                                                  'building_name'],
                                                                              name=filename)


class DrawingFile(models.Model):
    file_field = models.FileField(upload_to=directory_path)
    file_name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.file_name


class Drawing(models.Model):
    class DesignStage(models.TextChoices):
        ds1 = 'PW', _('Projekt wykonawczy')
        ds2 = 'PB', _('Projekt budowlany')
        ds3 = 'PK', _('Projekt koncepcyjny')

    class Branch(models.TextChoices):
        b1 = 'A', _('Architektura')
        b2 = 'K', _('Konstrukcja')
        b3 = 'E', _('Instalacje elektryczne')
        b4 = 'IS', _('Instalacje sanitarne')
        b5 = 'D', _('Drogi')

    design_stage = models.CharField(max_length=3, choices=DesignStage.choices, default=DesignStage.ds1)
    branch = models.CharField(max_length=3, choices=Branch.choices, default=Branch.b1)
    date_drawing = models.DateField()
    date_update = models.DateField()
    draw_number = models.CharField(max_length=10)
    draw_title = models.CharField(max_length=200)
    building_name = models.ForeignKey(BuildingName, on_delete=models.CASCADE)
    revision = models.CharField(max_length=3)
    file = models.ForeignKey(DrawingFile, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.file


class DrawingUser(models.Model):

    class Status(models.TextChoices):
        s1 = 'accepted', _('accepted')
        s2 = 'to correct', _('to correct')
        s3 = 'uploaded', _('uploaded')
        __empty__ = _(' ')

    drawing = models.ForeignKey(Drawing, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    date = models.DateTimeField()
    comment = models.TextField(max_length=1400, blank=True)
    status = models.CharField(max_length=100, choices=Status.choices, blank=True)

drawingdoc/views.py
import os
import shutil

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import CreateView, View, ListView, DeleteView, UpdateView

from ConstrManagementProject.settings import BASE_DIR, MEDIA_ROOT
from .custommixins import CustomPermMixin
from .form import BuildingNameForm, UploadDrawingForm, ProjectForm, DrawingsSearchForm, MembersOfProjectForm, \
    DrawingUserForm
from django.http import HttpResponseRedirect, Http404, FileResponse, HttpResponse
from .models import DrawingFile, Drawing, BuildingName, Project, MemberOfProject, DrawingUser
from .drawingsnamechecker import drawings_name_checker
from .fileschecker import files_checker
from datetime import datetime, timezone

from .utils import menu


class ProjectListView(CustomPermMixin, View):
    template_name = 'drawingdoc/projects_list.html'
    permission_required = 'drawingdoc.view_project'

    def get(self, request, *args, **kwargs):
        user = request.user
        user_projects = MemberOfProject.objects.filter(user=user).all()
        return render(request, self.template_name, {'object_list': user_projects,
                                                    'menu': menu,
                                                    })


class ProjectInfoView(CustomPermMixin, View):
    template_name = 'drawingdoc/project_info.html'
    permission_required = 'drawingdoc.view_project'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        building_names = BuildingName.objects.filter(project=project.id).all()
        uploaded_drawings = DrawingUser.objects.raw('''SELECT D.id, F.file_name, A.date, U.email 
                                                            FROM drawingdoc_drawing AS D
                                                            JOIN 
                                                            (SELECT * FROM 
                                                            (SELECT * FROM drawingdoc_drawinguser As AAA ORDER BY AAA.date DESC)
                                                            AS AA GROUP BY AA.drawing_id)
                                                            AS A
                                                            On D.id = A.drawing_id
                                                            JOIN users_customuser AS U
                                                             On U.id = A.user_id
                                                            JOIN drawingdoc_drawingfile AS F
                                                             On F.id = D.file_id
                                                             WHERE A.status = 'uploaded'
                                                             GROUP BY D.id
                                                             ORDER BY A.date DESC
                                                            ''')
        drawings_to_correct = DrawingUser.objects.raw('''SELECT D.id, F.file_name, A.date, U.email 
                                                            FROM drawingdoc_drawing AS D
                                                            JOIN 
                                                            (SELECT * FROM 
                                                            (SELECT * FROM drawingdoc_drawinguser As AAA ORDER BY AAA.date DESC)
                                                            AS AA GROUP BY AA.drawing_id)
                                                            AS A
                                                            On D.id = A.drawing_id
                                                            JOIN users_customuser AS U
                                                             On U.id = A.user_id
                                                            JOIN drawingdoc_drawingfile AS F
                                                             On F.id = D.file_id
                                                             WHERE A.status = 'to correct'
                                                             GROUP BY D.id
                                                             ORDER BY A.date DESC
                                                            ''')

        return render(request, self.template_name, {'project': project,
                                                    'building_list': building_names,
                                                    'menu': menu,
                                                    'uploaded_drawings': uploaded_drawings,
                                                    'drawings_to_correct': drawings_to_correct,
                                                    })


class NewBuildingName(CustomPermMixin, View):
    form_class = BuildingNameForm
    template_name = 'drawingdoc/newbuildingname.html'
    permission_required = 'drawingdoc.add_buildingname'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        return render(request, self.template_name, {'form': form,
                                                    'menu': menu,
                                                    'project': project
                                                    })

    def post(self, request, *args, **kwargs):
        try:
            project = Project.objects.get(id=kwargs['pk_p'])
        except Project.DoesNotExist:
            raise Http404("Project does not exist")
        form = self.form_class(request.POST)
        if form.is_valid():
            building_name = BuildingName(
                name=form.cleaned_data['name'],
                abbreviation=form.cleaned_data['abbreviation'].upper(),
                project=project,
            )
            building_name.save()
            return HttpResponseRedirect(reverse_lazy('project:project-info', kwargs={"pk_p": kwargs["pk_p"]}))
        return render(request, self.template_name, {'form': form})


class BuildingNameDeleteView(CustomPermMixin, View):
    permission_required = 'drawingdoc.delete_buildingname'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        building_name = get_object_or_404(BuildingName, pk=kwargs['pk_bn'])
        drawing_list = Drawing.objects.filter(building_name=building_name, project=project)
        for drawing in drawing_list:
            file_url = str(drawing.file.file_field.path)
            if os.path.isfile(file_url):
                os.remove(file_url)
            drawing.file.delete()
        building_name.delete()
        return HttpResponseRedirect(reverse_lazy('project:project-info', kwargs={"pk_p": self.kwargs["pk_p"]}))


class BuildingNameUpdateView(CustomPermMixin, UpdateView):
    form_class = BuildingNameForm
    model = BuildingName
    pk_url_kwarg = "pk_bn"
    template_name = 'drawingdoc/newbuildingname.html'
    permission_required = 'drawingdoc.change_buildingname'

    def get_success_url(self):
        return reverse_lazy('project:project-info', kwargs={"pk_p": self.kwargs["pk_p"]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu']=menu
        context['project'] = get_object_or_404(Project, pk=self.kwargs["pk_p"])
        return context


class NewProjectView(CustomPermMixin, View):
    form_class = ProjectForm
    template_name = 'drawingdoc/newbuildingname.html'
    permission_required = 'drawingdoc.add_project'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form,
                                                    'menu': menu})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            project = Project(
                name=form.cleaned_data['name'],
                abbreviation=form.cleaned_data['abbreviation'].upper(),
                creator=get_user_model().objects.get(id=request.user.id),
            )
            project.save()
            content_type = ContentType.objects.get_for_model(Project)
            permission = Permission.objects.create(
                codename='project_'+str(project.id),
                name='Can use project with id='+str(project.id),
                content_type=content_type,
            )
            permission.save()
            user=request.user
            user.user_permissions.add(permission)
            user.save()
            member_of_project = MemberOfProject(
                user=user,
                project=project
            )
            member_of_project.save()
            return HttpResponseRedirect(reverse_lazy('project:project-list'))
        return render(request, self.template_name, {'form': form})


class AddUserToProjectView(CustomPermMixin, View):
    form_class = MembersOfProjectForm
    template_name = 'drawingdoc/newbuildingname.html'
    permission_required = 'drawingdoc.add_memberofproject'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        form = self.form_class()
        return render(request, self.template_name, {'form': form,
                                                    'menu': menu,
                                                    'project': project,
                                                    })

    def post(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])

drawingdoc/templates/drawingdoc/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block heads %}

    {% endblock %}
	<link type="text/css" href="{% static 'drawingdoc/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
	{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="/"><div class="logo">Home</div></a></li>
			{% if request.user.is_authenticated %}
				{% for m in menu %}
					<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
				{% endfor %}
			{% endif %}
				{% if request.user.is_authenticated %}
				<li class="last"> {{user.username}} | <a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li class="last"><a href="{% url 'registration' %}">Registration</a> | <a href="{% url 'login' %}">Login</a></li>
				{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
	{% endblock mainmenu %}

<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar left -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
{% if project %}
		<li><a href='{% url "project:project-info" project.id %}'><span class="project-name">{{project.name}}</span></a></li>
		<li></li>
		<li><a href='{% url "project:building-name-create" project.id %}'>Create building name</a></li>
		<li><a href='{% url "project:drawing-document-list" project.id %}'>Drawing documents</a></li>
		<li><a href='{% url "project:drawing-document-upload" project.id %}'>Upload drawings</a></li>
		<li><a href='{% url "project:members" project.id %}'>User management</a></li>
		<li><a href='{% url "project:schedule-info" project.id %}'>Schedule</a></li>
		<li><a href='{% url "project:schedule-view" project.id %}'>Gantt Schedule</a></li>
{% endif %}

	</ul>
</td>
<!-- end Sidebar'а -->

<td valign="top" class="content">
<!-- Content -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- End content-->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<span>&copy; Made with Love by YI</span>
	</div>
</td></tr></table>
<!-- End footer and page -->
</body>
</html>

drawingdoc/templates/drawingdoc/drawing_info.html
{% extends 'drawingdoc/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block heads %}
<title>List drawings</title>
<link rel="stylesheet" href="{% static 'drawingdoc/css/drawing_info_view.css'%}">
{% endblock %}

{% block content %}
<h3>Drawing {{ obj.file.file_name }}</h3>
<table border="1">
	<thead>
	  <tr>
		  <th>Drawing status</th>
		  <th>Design stage</th>
		  <th>Branch</th>
		  <th>Building name</th>
		  <th>Number of drawing</th>
		  <th>Revision</th>
		  <th>Drawing revision date</th>
		  <th>Title of drawing</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
		  <td>{{ dr_status.status }}</td>
		  <td>{{ obj.design_stage }}</td>
		  <td>{{ obj.branch }}</td>
		  <td>{{ obj.building_name }}</td>
		  <td>{{ obj.draw_number }}</td>
		  <td>{{ obj.revision }}</td>
		  <td>{{ obj.date_drawing|date:"d/m/Y" }}</td>
		  <td>{{ obj.draw_title|default:" "  }}</td>
	  </tr>
	</tbody>

</table>

<br>

<table border="1">
	<tbody>
	  <tr>
		  <td><a href="delete/">Delete</a></td>
		  <td><a href="update/">Update</a></td>
		  <td><a href="{{obj.file.file_field.url}}">Download</a></td>

	  </tr>
	</tbody>
</table>
<br>
<iframe src="{{obj.file.file_field.url}}" width="1000" height="800" frameborder="1"></iframe>
<br>
<table border="0" >
	<tbody>
	{% for activity in activities %}

	{% if activity.status %}

	<tr>
		<td>{{activity.date|date:"d M Y"}}</td>
		<td>{{activity.date|time:"H:i"}}</td>
		<td>{{activity.user.email}}</td>
		<td><span style="color: red">Drawing {{activity.status}}</span></td>
	</tr>

	{% endif %}

	{% if activity.comment %}

	<tr>
		  <td>{{activity.date|date:"d M Y"}}</td>
		  <td>{{activity.date|time:"H:i"}}</td>
		  <td>{{activity.user.email}}</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td>{{activity.comment|linebreaks}}</td>
	</tr>

	{% endif %}

	{% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
<form id="contact" action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
	<br>
    <input type="submit" value="Submit">
</form>

{% endblock %}

drawingdoc/templates/drawingdoc/drawings_list.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>List drawings</title>
{% endblock %}
{% block content %}

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
{% if object_dict %}
<table border="1">
	<caption>Drawing documentation</caption>
	<thead>
	  <tr>
		<th>Draw number</th>
		<th>Building<br>abbreviation</br></th>
		<th>Draw title</th>
		{% for rev in revision_list %}

		<th>Revision {{ rev }}</th>
		{% endfor %}
	  </tr>
	</thead>
	<tbody>

	{% for number, object in object_dict.items %}
	  <tr>
		<td>{{ object.obj.draw_number }}</td>
		<td>{{ object.obj.building_name__abbreviation }}</td>
		<td>{{ object.obj.draw_title|default:" "  }}</td>
		{% for rev in revision_list %}
		  {% if rev in object.all_rev %}
			  {% for rev_date in object.rev_date %}
					{% if rev == rev_date.revision %}
						<td><a href='../{{ rev_date.id }}'>{{ rev_date.date_drawing|date:"d/m/Y" }}</a></td>
					{% endif %}
			  {% endfor %}
		  {% else %}
		  	<td></td>
		  {% endif %}
		{% endfor %}
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
{% endif %}

{% endblock %}

drawingdoc/templates/drawingdoc/generic_delete.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Delete Drawing</title>
{% endblock %}

{% block content %}
<h1>Confirm removing "{{object.name}} "</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

drawingdoc/templates/drawingdoc/home.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Home</title>
{% endblock %}


{% block content %}
<h3><b>CONSTRUCTION PROJECT MANAGEMENT SYSTEM</b></h3>

<h4><b>Features</b></h4>
<li>Interface to create your Users with email checking</li>
<li>Create Projects, add members to project, upload drawing documents, update infos, add comments for drawing, change drawing status</li>
<li>Login and Logout</li>

{% endblock %}

drawingdoc/templates/drawingdoc/members_of_project_list.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Members of project {{ project.name }} </title>
{% endblock %}


{% block content %}
<h4><a href='{% url "project:members-add" project.id %}'>Add a new member</a></h4>
<table border="1">
	<thead>
	  <tr>
		  <th>First Name</th>
		  <th>Last Name</th>
		  <th>Status</th>
		  <th>Action</th>
	  </tr>
	</thead>
	<tbody>

	{% for member in members_of_project %}
	  <tr>
		  <td>{{ member.user.first_name }}</td>
		  <td>{{ member.user.last_name }}</td>
		  <td>{{ member.user.status }}</td>
		  <td><a href='{% url "project:members-delete" project.id member.id %}'>Delete</a></td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>


{% endblock %}

drawingdoc/templates/drawingdoc/newbuildingname.html
{% extends 'drawingdoc/base.html' %}
{% load crispy_forms_tags %}
{% block heads %}
<title>Nazwa budynku</title>
{% endblock %}

{% block content %}
<form id="contact" action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

drawingdoc/templates/drawingdoc/project_info.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Project {{project.name}}</title>
{% endblock %}


{% block content %}
<table border="1">
	<caption>Building name list</caption>
	<thead>
	  <tr>
		  <th>Building name</th>
		  <th>Abbreviation</th>
		  <th>Action</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in building_list %}
	  <tr>
		  <td>{{ obj.name }}</td>
		  <td>{{ obj.abbreviation }}</td>
		  <td><a href='{% url "project:building-name-update" obj.project.id obj.id %}'>Update</a>
			  <a href='{% url "project:building-name-delete" obj.project.id obj.id %}'>Delete</a></td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
<br>

<table border="1">
	<caption>Uploaded drawings</caption>
	<thead>
	  <tr>
		  <th>Drawing name</th>
		  <th>Date upload</th>
		  <th>User email</th>
	  </tr>
	</thead>
	<tbody>

	{% for draw_user in uploaded_drawings %}
	  <tr>
		  <td><a href='{% url "project:drawing-document-info" project.id draw_user.id %}'>{{draw_user.file_name}}</a></td>
		  <td>{{ draw_user.date|date:"d/m/Y"}}</td>
		  <td>{{ draw_user.email }}</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
<br>

<table border="1">
	<caption>Drawings to correct</caption>
	<thead>
	  <tr>
		  <th>Drawing name</th>
		  <th>Verification date</th>
		  <th>User email</th>
	  </tr>
	</thead>
	<tbody>

	{% for draw_user in drawings_to_correct %}
	  <tr>
		  <td><a href='{% url "project:drawing-document-info" project.id draw_user.id %}'>{{draw_user.file_name}}</a></td>
		  <td>{{ draw_user.date |date:"d/m/Y"}}</td>
		  <td>{{ draw_user.email }}</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>
<br>
<br>

<h4><a href='{% url "project:project-delete" project.id %}'>Delete project</a></h4>

{% endblock %}

drawingdoc/templates/drawingdoc/projects_list.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Project list</title>
{% endblock %}


{% block content %}
<h3>Project list</h3>

<table border="1">
	<thead>
	  <tr>
		<th>Project name</th>
		<th>Abbreviation</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td><a href='{% url "project:project-info" obj.project.id %}'>{{ obj.project.name }}</a></td>
		<td>{{ obj.project.abbreviation }}</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>


{% endblock %}

drawingdoc/templates/drawingdoc/uploaddrawing.html
{% extends 'drawingdoc/base.html' %}
{% load crispy_forms_tags %}

{% block heads %}
<title>Upload Drawing</title>
{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy}}

      <button type="submit">Upload</button>
</form>

{% endblock %}