ConstrManagementProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path
from drawingdoc.views import HomeView, media_access


urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include(('drawingdoc.urls','project'), namespace='project')),
    path('', HomeView.as_view()),
    path('', include('users.urls')),
    re_path(r'^media/(?P<path>.*)', media_access, name='media')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drawingdoc/urls.py
from django.urls import path, reverse_lazy, include
from django.views.generic import RedirectView

from .views import NewBuildingName, UploadDrawingView, NewProjectView, DrawingsListView, DrawingInfoView, \
    DrawingDeleteView, DrawingUpdateView, ProjectListView, ProjectInfoView, BuildingNameDeleteView,\
    BuildingNameUpdateView, ProjectDeleteView, AddUserToProjectView, MemberOfProjectListView, MemberOfProjectDeleteView



urlpatterns = [
    path('', RedirectView.as_view(url='list/')),
    path('new/', NewProjectView.as_view(), name='project-new'),
    path('list/', ProjectListView.as_view(), name='project-list'),
    path('<int:pk_p>/', ProjectInfoView.as_view(), name='project-info'),
    path('<int:pk_p>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('<int:pk_p>/members/', MemberOfProjectListView.as_view(), name='members'),
    path('<int:pk_p>/members/add/', AddUserToProjectView.as_view(), name='members-add'),
    path('<int:pk_p>/members/<int:pk_m>/delete/', MemberOfProjectDeleteView.as_view(), name='members-delete'),
    path('<int:pk_p>/building_name/<int:pk_bn>/delete/', BuildingNameDeleteView.as_view(),name='building-name-delete'),
    path('<int:pk_p>/building_name/<int:pk_bn>/update/', BuildingNameUpdateView.as_view(),name='building-name-update'),
    path('<int:pk_p>/new_building_name/', NewBuildingName.as_view(), name='building-name-create'),
    path('<int:pk_p>/drawing_documents/upload/', UploadDrawingView.as_view(),name='drawing-document-upload'),
    path('<int:pk_p>/drawing_documents/list/', DrawingsListView.as_view(),name='drawing-document-list'),
    path('<int:pk_p>/drawing_documents/<int:pk>/', DrawingInfoView.as_view(),name='drawing-document-info'),
    path('<int:pk_p>/drawing_documents/<int:pk>/delete/', DrawingDeleteView.as_view()),
    path('<int:pk_p>/drawing_documents/<int:pk>/update/', DrawingUpdateView.as_view()),
    path('<int:pk_p>/schedule/', include('schedule.urls')),
]

users/urls.py
from django.urls import path, include
from .views import RegisterUserView, CustomLoginView, CustomLogoutView, activate, activate_info
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('registration/', RegisterUserView.as_view(), name='registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('activating/', activate_info, name='activate-info'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

# Create your models here.


class CustomUser(AbstractUser):

    class Status(models.TextChoices):
        s1 = 'AR', _('Architekt')
        s2 = 'INW', _('Inwestor')
        s3 = 'GW', _('Generalny Wykonawca')
        s4 = 'INI', _('Inspektor Nadzoru Inwestorskiego')

    email = models.EmailField(unique=True)
    status = models.CharField(max_length=100, choices=Status.choices, default=Status.s2)

    def __str__(self):
        return self.username

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View

from .custommixins import UserAuthenticatingMixin
from .tokens import account_activation_token
from .form import UserRegistrationForm, CustomAuthenticationForm
from .permissions import status_permision


# Create your views here.

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=int(uid))
    except:
        user =None

    if user is not None and account_activation_token.check_token(user,token):
        user.is_active = True
        user.user_permissions.set(status_permision[user.status])
        user.save()
        return redirect('login')
    return redirect('registration')


def activate_info(request):
    return render(request, template_name='users/activate_info.html')


def activate_email(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string('users/template_activate_account.html',{
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        pass


class RegisterUserView(UserAuthenticatingMixin, View):
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    redirect_url = '/'

    def test_func(self):
        return not self.request.user.is_authenticated

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activate_email(request, user, form.cleaned_data.get('email'))
            return HttpResponseRedirect(reverse_lazy('activate-info'))
        return render(request, self.template_name, {'form': form})


class CustomLoginView(UserAuthenticatingMixin, View):
    form_class = CustomAuthenticationForm
    template_name = 'users/registration.html'
    redirect_url = '/'

    def test_func(self):
        return not self.request.user.is_authenticated

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                return redirect('/')
        return render(request, self.template_name, {'form': form})


class CustomLogoutView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/')

users/templates/users/activate_info.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block heads %}
<title>Activate account information</title>
{% endblock %}

{% block content %}
<br>
<div><h3>Dear User, please go to your email inbox and click on received activation link to confirm and complete the registration. Note: check your spam folder.</h3></div>

{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block heads %}

    {% endblock %}
	<link type="text/css" href="{% static 'drawingdoc/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
	{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="/"><div class="logo">Home</div></a></li>
			{% if request.user.is_authenticated %}
				{% for m in menu %}
					<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
				{% endfor %}
			{% endif %}
				{% if request.user.is_authenticated %}
				<li class="last"> {{user.username}} | <a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li class="last"><a href="{% url 'registration' %}">Registration</a> | <a href="{% url 'login' %}">Login</a></li>
				{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
	{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar left -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
{% if project %}
		<li><a href='{% url "project:project-info" project.id %}'><span class="project-name">{{project.name}}</span></a></li>
		<li></li>
		<li><a href='{% url "project:building-name-create" project.id %}'>Create building name</a></li>
		<li><a href='{% url "project:drawing-document-list" project.id %}'>Drawing documents</a></li>
		<li><a href='{% url "project:drawing-document-upload" project.id %}'>Upload drawings</a></li>
		<li><a href='{% url "project:members" project.id %}'>User management</a></li>
{% endif %}

	</ul>
</td>
<!-- end Sidebar'а -->

<td valign="top" class="content">
<!-- Content -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- End content-->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<span>&copy; Made with Love by YI</span>
	</div>
</td></tr></table>
<!-- End footer and page -->
</body>
</html>

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block heads %}
<title>Registration</title>
{% endblock %}

{% block content %}
<form id="contact" action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

users/templates/users/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}