ConstrManagementProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path
from drawingdoc.views import HomeView, media_access


urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include(('drawingdoc.urls','project'), namespace='project')),
    path('', HomeView.as_view()),
    path('', include('users.urls')),
    re_path(r'^media/(?P<path>.*)', media_access, name='media')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schedule/urls.py
from django.urls import path, reverse_lazy, include
from django.views.generic import RedirectView

from .views import UploadCsvView, ScheduleGantView, ScheduleInfoView, ScheduleDeleteView

urlpatterns = [
    path('', ScheduleInfoView.as_view(), name='schedule-info'),
    path('upload/', UploadCsvView.as_view(), name='schedule-upload'),
    path('delete/', ScheduleDeleteView.as_view(), name='schedule-delete'),
    path('view/', ScheduleGantView.as_view(), name='schedule-view'),
]

users/urls.py
from django.urls import path, include
from .views import RegisterUserView, CustomLoginView, CustomLogoutView, activate, activate_info
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('registration/', RegisterUserView.as_view(), name='registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('activating/', activate_info, name='activate-info'),
]

schedule/models.py
from django.db import models
from drawingdoc.models import Project


class Schedule(models.Model):
    old_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=250, blank=True)
    date_start = models.DateField()
    date_finish = models.DateField()
    predecessors = models.CharField(max_length=100, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    outline_level = models.IntegerField()
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.name

schedule/views.py
import json

from django.db.models.functions import Concat, Extract, Trunc
from django.http import HttpResponseRedirect, Http404

from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views import View
from django.db.models import CharField, Value as V, DateTimeField, DateField, F

from drawingdoc.custommixins import CustomPermMixin
from drawingdoc.models import Project
from drawingdoc.utils import menu
from schedule.form import UploadScheduleForm
import pandas

from schedule.models import Schedule
from schedule.serializers import ScheduleSerializer, ScheduleExportSerializer


class UploadCsvView(CustomPermMixin, View):
    form_class = UploadScheduleForm
    template_name = 'drawingdoc/uploaddrawing.html'
    permission_required = 'schedule.add_schedule'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        return render(request, self.template_name, {'form': form,
                                                    'menu': menu,
                                                    'project': project})

    def post(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        schedule = Schedule.objects.filter(project=project)
        if schedule:
            schedule.delete()
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            csv = pandas.read_csv(request.FILES['file_csv'])
            schedule_dicts = csv.to_dict(orient="index")
            for dict_s in schedule_dicts.values():
                dict_s['project'] = project.id
                dict_s['outline_level'] = dict_s.get('Outline Level', None)
            serializer = ScheduleSerializer(data=list(schedule_dicts.values()), many=True)
            print(list(schedule_dicts.values())[0])
            if serializer.is_valid():
                serializer.save()
                return HttpResponseRedirect(reverse_lazy('project:schedule-info', kwargs={"pk_p": kwargs["pk_p"]}))
            else:
                for error_dict in serializer.errors:
                    if error_dict:
                        for error in error_dict.values():
                            form.add_error('file_csv', error)
                form.clean()
        return render(request, self.template_name, {'form': form,
                                                    'menu': menu,
                                                    'project': project})


class ScheduleGantView(CustomPermMixin, View):
    template_name = 'schedule/schedule_view.html'
    permission_required = 'schedule.view_schedule'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        tasks = Schedule.objects.filter(project=project).annotate(start=Trunc('date_start','day',output_field=DateField()),
                                          end=Trunc('date_finish','day',output_field=DateField()),
                                          _id=Concat(V('ask '), 'old_id',output_field=CharField()),
                                          ).values('start', 'end', '_id', 'name','progress', 'predecessors'
                                                   ).annotate(id=Concat(V('T'),"_id",output_field=CharField()),
                                                              dependencies=F('predecessors')
                                                              ).values('start', 'end', 'id', 'name',
                                                                       'progress','dependencies')
        serializer = ScheduleExportSerializer(tasks, many=True)
        return render(request, self.template_name, {'menu': menu,
                                                    'project': project,
                                                    'tasks': json.dumps(serializer.data)})


class ScheduleInfoView(CustomPermMixin, View):
    template_name = 'schedule/schedule_info.html'
    permission_required = 'schedule.view_schedule'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        return render(request, self.template_name, {'menu': menu,
                                                    'project': project})


class ScheduleDeleteView(CustomPermMixin, View):
    permission_required = 'schedule.delete_schedule'

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk_p'])
        schedule = Schedule.objects.filter(project=project)
        if schedule:
            schedule.delete()
            return HttpResponseRedirect(reverse_lazy('project:schedule-info', kwargs={"pk_p": kwargs["pk_p"]}))
        raise Http404("Schedule does not exist")

schedule/templates/schedule/schedule_info.html
{% extends 'drawingdoc/base.html' %}

{% block heads %}
<title>Schedule of project</title>
{% endblock %}

{% block content %}

<table border="1">
	<tbody>
	  <tr>
		  <td><a href='{% url "project:schedule-upload" project.id %}'>Upload</a></td>
		  <td><a href='{% url "project:schedule-delete" project.id %}'>Delete</a></td>

	  </tr>
	</tbody>
</table>


{% endblock %}

schedule/templates/schedule/schedule_view.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Simple Gantt</title>
	<style>
		body {
			font-family: sans-serif;
			background: #ccc;
		}
		.container {
			width: 80%;
			margin: 0 auto;
		}
		/* custom class */
		.gantt .bar-milestone .bar {
			fill: tomato;
		}
		.heading {
			text-align: center;
		}
	</style>
	<script src="{% static 'schedule/js/frappe-gantt.js'%}"></script>
    <link rel="stylesheet" href="{% static 'schedule/css/frappe-gantt.css'%}" />
</head>
<body>
	<div class="container">
		<h2 class="heading">Interactive Gantt Schedule</h2>
		<div class="gantt-target"></div>
	</div>
	<br>
	<script>
		var tasks = JSON.parse("{{tasks|escapejs}}");

		var gantt_chart = new Gantt(".gantt-target", tasks, {
			on_click: task => {
				console.log(task);
			},
			on_date_change: (task, start, end) => {
				console.log(task, start, end);
			},
			on_progress_change: (task, progress) => {
				console.log(task, progress);
			},
			on_view_change: function (mode) {
				console.log(mode);
			},
			view_modes: ['Quarter Day', 'Half Day', 'Day', 'Week', 'Month'],
			bar_height: 20,
			view_mode: 'Month',
    		bar_corner_radius: 3,

		});
		gantt_chart.change_view_mode('Month') // Quarter Day, Half Day, Day, Week, Month
		console.log(gantt_chart);

	</script>
</body>
</html>